title: An adventurer's journal to GSoC 2018 at LEAP!
email: vdegou@gmail.com
description: >- 
  This is an adventurer's journal following the progress of the young knight, V, in his quest to create the greatest Password Manager of the land. A secure Password Manager to rule them all!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
