title: An adventurer's journal to GSoC 2018 at LEAP!
email: vdegou@gmail.com
description: >- 
  This is an adventurer's journal following the progress of the young knight, V, in his quest to create the greatest Password Manager of the land. A secure Password Manager to rule them all!
baseurl: /GSoC2018

github_username:  DiffyA

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
